name: Github Actions Demo
on:
  push:
    branches:
      - main
jobs:
  greeting:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'main' || 'development' }}
    steps:
      - name: Setup Node,js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: install dependencies
        run: npm i ngx-lazy-directive
