name: Github Actions Demo
on:
  push:
    branches:
      - main
jobs:
  greeting:
    runs-on: ubuntu-latest
    if: ${{ vars.TEST == 'Tu Phan' }}
    steps:
      - name: Print greeting
        run: echo "Hello, World!"
