name: Github Actions Demo
on:
  push:
    branches:
      - main
jobs:
  greeting:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Print greeting
        run: echo "${{ vars.E_TEST }}"
