name: Github Actions Demo
on:
  push:
    branches:
      - main
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        env:
          GREETING: ${{ secrets.SECRET_KEY }}
        run: echo $GREETING
