name: Github Actions Demo
on:
  push:
    branches:
      - main
jobs:
  greeting:
    runs-on: ubuntu-latest
    env:
      TEST: ${{ vars.TEST }}
    steps:
      - name: Print greeting
        run: echo $TEST
