name: Pull Request Review Enforcement
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted, dismissed]

jobs:
  check-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required reviews
        uses: actions/github-script@v6
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const approvals = reviews.filter(review => review.state === 'APPROVED');

            if (approvals.length < 1) {
              core.setFailed('At least one reviewer approval is required before merging');
            } else {
              console.log(`✅ Found ${approvals.length} approval(s)`);
            }
