name: Pull Request Review Enforcement
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted, dismissed]

permissions:
  models: read
  actions: write
  statuses: write
  checks: write
  contents: read
  pull-requests: read

jobs:
  copilot-tasks:
    runs-on: ubuntu-latest
    environment:
      name: "main"
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Print
        run: echo "Running Copilot tasks for PR review enforcement ${{ vars.E_TEST }}"

      - name: Verify GitHub CLI authentication
        run: |
          gh auth status
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Install and Configure Copilot CLI
        run: |
          gh extension install github/gh-copilot
          # Handle the data collection prompt non-interactively
          printf "No\n" | gh copilot config 2>/dev/null || true
          gh copilot --version
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GH_PROMPT_DISABLED: true

      - name: Run Copilot tasks
        run: |
          gh copilot suggest "Review this pull request and provide feedback on the code quality, potential issues, and improvements."
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GH_PROMPT_DISABLED: true
