name: Pull Request Review Enforcement
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted, dismissed]

permissions:
  statuses: write
  checks: write
  contents: read
  pull-requests: read

jobs:
  copilot-tasks:
    runs-on: ubuntu-latest
    environment:
      name: "main"
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install Copilot CLI
        run: |
          gh extension install github/gh-copilot
          gh copilot --version
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          GH_COPILOT_USAGE_COLLECTION: "off"
      - name: Run Copilot tasks
        run: |
          gh copilot suggest "Review this pull request and provide feedback on the code quality, potential issues, and improvements."
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          GH_COPILOT_USAGE_COLLECTION: "off"
