name: Pull Request Review Enforcement
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted, dismissed]

permissions:
  statuses: write
  checks: write
  contents: read
  pull-requests: read

jobs:
  check-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: fail-for-do-not-merge
        run: |
          exit 1
