name: Pull Request Review Enforcement
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted, dismissed]

permissions:
  models: read
  actions: write
  statuses: write
  checks: write
  contents: read
  pull-requests: read

jobs:
  copilot-tasks:
    runs-on: ubuntu-latest
    environment:
      name: "main"
    env:
      GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      GH_PROMPT_DISABLED: true
      GH_COPILOT_USAGE_COLLECTION: "off"
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Verify GitHub CLI authentication
        run: |
          gh auth status

      - name: Install and Configure Copilot CLI
        run: |
          gh extension install github/gh-copilot
          gh copilot --version
      - name: Run Copilot tasks
        run: |
          gh copilot suggest "Review this pull request and provide feedback on the code quality, potential issues, and improvements."
